/**
 * Common error codes used throughout the application
 */

export enum ErrorCode {
  // General errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  
  // Authentication errors
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  
  // Blockchain errors
  BLOCKCHAIN_ERROR = 'BLOCKCHAIN_ERROR',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  
  // Gift related errors
  GIFT_CREATION_FAILED = 'GIFT_CREATION_FAILED',
  GIFT_NOT_FOUND = 'GIFT_NOT_FOUND',
  GIFT_ALREADY_CLAIMED = 'GIFT_ALREADY_CLAIMED',
  
  // Wallet related errors
  WALLET_GENERATION_FAILED = 'WALLET_GENERATION_FAILED',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS'
}

export default ErrorCode; 